import {defineType, defineField} from 'sanity';

export const publication = defineType({
  name: 'publication',
  type: 'document',
  title: 'Publication',
  fields: [
    defineField({name: 'title', type: 'string', title: 'Title', validation: (rule) => rule.required()}),
    defineField({name: 'titleAr', type: 'string', title: 'Title (Arabic)'}),
    defineField({name: 'slug', type: 'slug', title: 'Slug', options: {source: 'title', maxLength: 96}}),
    defineField({name: 'code', type: 'string', title: 'Code', description: 'Short monogram such as TOM, SOC'}),
    defineField({name: 'publishedMonth', type: 'string', title: 'Published Month', description: 'ISO month 01-12'}),
    defineField({name: 'publishedYear', type: 'number', title: 'Published Year'}),
    defineField({name: 'publishedDate', type: 'date', title: 'Published Date', options: {dateFormat: 'YYYY-MM-DD'}}),
    defineField({name: 'summary', type: 'text', title: 'Summary'}),
    defineField({name: 'summaryAr', type: 'text', title: 'Summary (Arabic)'}),
    defineField({name: 'body', type: 'array', title: 'Body', of: [{type: 'block'}]}),
    defineField({name: 'bodyAr', type: 'array', title: 'Body (Arabic)', of: [{type: 'block'}]}),
    defineField({
      name: 'authors',
      type: 'array',
      title: 'Authors',
      description: 'Free-text author names; use this instead of linking to people',
      of: [{type: 'string'}],
    }),
    defineField({
      name: 'authorsAr',
      type: 'array',
      title: 'Authors (Arabic)',
      description: 'Free-text author names in Arabic',
      of: [{type: 'string'}],
    }),
    defineField({name: 'topics', type: 'array', title: 'Topics/Tags', of: [{type: 'string'}]}),
    defineField({name: 'topicsAr', type: 'array', title: 'Topics/Tags (Arabic)', of: [{type: 'string'}]}),
    defineField({name: 'heroImageUrl', type: 'url', title: 'Hero Image URL (legacy)', description: 'Optional direct URL for images imported from legacy data'}),
    defineField({name: 'heroImage', type: 'image', title: 'Hero Image', options: {hotspot: true}}),
    defineField({name: 'attachments', type: 'array', title: 'Attachments', of: [{type: 'file'}]}),
    defineField({name: 'notes', type: 'text', title: 'Notes/Notes (Legacy)'}),
    defineField({name: 'notesAr', type: 'text', title: 'Notes (Arabic)'}),
    defineField({name: 'pdfUrl', type: 'url', title: 'PDF URL'}),
    defineField({name: 'externalUrl', type: 'url', title: 'External URL'}),
    defineField({name: 'sourceUrl', type: 'url', title: 'Source URL'}),
  ],
  preview: {
    select: {title: 'title', subtitle: 'code', media: 'heroImage'},
    prepare: ({title, subtitle, media}) => ({title, subtitle: subtitle ? `Code: ${subtitle}` : undefined, media}),
  },
});